name: release
description: A small utility that allows to easily update your pubspec and your Github tags on new releases.
version: 0.1.5
homepage: https://github.com/Skyost/DartRelease
repository: https://github.com/Skyost/DartRelease
issue_tracker: https://github.com/Skyost/DartRelease/issues
funding:
  - https://ko-fi.com/Skyost
  - https://paypal.me/Skyost
topics:
  - tool
  - cli
  - release
  - changelog
executables:
  release:

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  args: ^2.7.0
  conventional_commit: ^0.6.1
  dotenv: ^4.2.0
  http: ^1.6.0
  liquify: '>=1.0.4 <2.0.0'
  meta: '>=1.16.0 <2.0.0'
  pub_semver: ^2.2.0
  yaml: ^3.1.3
  yaml_edit: ^2.2.3
  xml: ^6.6.1

dev_dependencies:
  flutter_lints: ^6.0.0

release:
  changelog:
    header: '# ðŸ“° `release` utility changelog'
